{{ if .Values.ingress.enabled }}
{{- $dot := . }}
{{- range $index, $ing := .Values.ingress.ingressList}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $dot.Release.Name }}-{{ $ing.name }}-ingress"
  annotations:
  {{- toYaml $ing.annotations | nindent 4 }}
spec:
  ingressClassName: "nginx"
  tls:
  {{- toYaml $ing.tls | nindent 8 }}

  rules:
  {{- tpl (toYaml $ing.rules) $ | nindent 8 }}

{{ end }}
{{ end }}