{{ if .Values.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}
type: Opaque
data:
  {{- $secEnvs := .Values.env.secrets -}}
  {{- range $key, $val := $secEnvs}}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
{{- end }}
  