kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-service"
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: management
      protocol: TCP
      port: {{ .Values.service.managementPort }}